version: "3"

services:
  react-app:
    build: ./react-app
    volumes:
      - ./react-app:/usr/src/app
    command: npm start
    ports:
      - "3000:3000"

  backend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    command: /bin/sh -c "npm i && npm run dev"

  database:
    build: ./database  # Dockerfileの親フォルダパス
    container_name: mysql-container  # コンテナ名
    hostname: mysql-server  # ホスト名
    platform: linux/x86_64
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - ./database/data:/var/lib/mysql  # volumeのエントリポイント
      - ./database/my.cnf:/etc/mysql/conf.d/my.cnf  # cnfファイル
      - ./database/sql/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql # 起動時に実行するsqlファイル
    env_file:
      - ./database/sql.env
    environment:
      TZ: Japan
    ports:
      - 3306:3306
    restart: always